language: objective-c

install:
  # - npm install

before_script:
  - chmod +x ./TestRock/RockCer/add-key.sh
  - cd ./TestRock/RockCer
  - ./add-key.sh
  - cd -

script:
  - chmod +x ./buildTestIpa.sh
  - ./buildTestIpa.sh
  - cd ./buildTemp && ls -R
  # - curl